development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: dev-db
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 5
  timeout: 5000

test:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: test-db
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 5
  timeout: 5000

production:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: prod-db
  username: root
  password: <%= ENV['mysql_password'] %>
  pool: 20
  timeout: 5000
